python dlrm_fae_avazu.py 	--arch-sparse-feature-size=16 \
						--arch-mlp-bot="2-512-256-64-16" \
						--arch-mlp-top="512-256-1" \
						--data-generation=avazu \
						--data-set=avazu \
						--raw-data-file=./input/avazu_with_id/train.txt \
						--processed-data-file=./input/avazu_with_id/train_processed.npz \
						--train-hot-file=./input/avazu_with_id/avazu_hot_cold/train_hot.npz \
						--train-normal-file=./input/avazu_with_id/avazu_hot_cold/train_normal.npz \
						--hot-emb-dict-file=./input/avazu_with_id/avazu_hot_cold/hot_emb_dict.npz \
						--loss-function=bce \
						--round-targets=True \
						--mini-batch-size=1024 \
						--print-freq=4096 \
						--print-time \
						--test-freq=10000
